from __future__ import annotations

import copy
import csv
import json
import shutil
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SOURCE_CSV = PROJECT_ROOT / "reports" / "human_scoring_pilot_preliminary.csv"
CONFIRMED_CSV = PROJECT_ROOT / "reports" / "human_scoring_pilot_confirmed.csv"
METRICS_PATH = PROJECT_ROOT / "reports" / "experiments" / "pilot_human_metrics.json"
PRELIMINARY_METRICS_ARCHIVE = PROJECT_ROOT / "reports" / "experiments" / "pilot_human_metrics_preliminary.json"
COMPARISON_JSON = PROJECT_ROOT / "reports" / "experiments" / "pilot_comparison.json"
COMPARISON_CSV = PROJECT_ROOT / "reports" / "experiments" / "pilot_comparison.csv"
COMPARISON_MD = PROJECT_ROOT / "reports" / "experiments" / "pilot_comparison.md"
ERROR_DRAFT = PROJECT_ROOT / "reports" / "experiments" / "pilot_error_analysis_draft.md"
ERROR_CONFIRMED = PROJECT_ROOT / "reports" / "experiments" / "pilot_error_analysis.md"
SUMMARY_CSV = PROJECT_ROOT / "reports" / "metrics_summary.csv"
SUMMARY_MD = PROJECT_ROOT / "reports" / "metrics_summary.md"
PILOT_REPORT_DIR = PROJECT_ROOT / "reports" / "experiments"

CONFIRMED_STATUS = "user_confirmed"
CONFIRMED_REVIEWER = "User-confirmed review of Codex-assisted scoring"
SCORE_FIELDS = ("correctness_score", "faithfulness_score", "hallucination", "over_refusal")
KEY_FIELDS = ("method", "question_id")


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def score_signature(rows: list[dict[str, str]]) -> list[tuple[str, ...]]:
    return [tuple(row[field] for field in (*KEY_FIELDS, *SCORE_FIELDS)) for row in rows]


def promote_csv() -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    source_rows = read_csv(SOURCE_CSV)
    if len(source_rows) != 160:
        raise ValueError(f"expected 160 preliminary scoring rows, got {len(source_rows)}")
    if any(row.get("review_status") != "preliminary_pending_user_confirmation" for row in source_rows):
        raise ValueError("source CSV is not the expected preliminary scoring artifact")

    confirmed_rows = []
    for source in source_rows:
        row = dict(source)
        row["reviewer"] = CONFIRMED_REVIEWER
        row["review_status"] = CONFIRMED_STATUS
        row["notes"] = (
            row["notes"]
            .replace(
                "有引用，但缺少足够结构证据，需人工核对引用与结论的一致性。",
                "有引用，但缺少足够结构证据；用户确认该忠实度评分为部分支持。",
            )
            .replace("需与 actual_decision 分开记录", "已与 actual_decision 分开确认")
        )
        confirmed_rows.append(row)

    if score_signature(source_rows) != score_signature(confirmed_rows):
        raise AssertionError("score values changed during confirmation promotion")
    write_csv(CONFIRMED_CSV, confirmed_rows, list(confirmed_rows[0]))
    return source_rows, confirmed_rows


def load_preliminary_metrics() -> dict:
    if not PRELIMINARY_METRICS_ARCHIVE.exists():
        if not METRICS_PATH.exists():
            raise FileNotFoundError(f"missing scoring metrics: {METRICS_PATH}")
        current = json.loads(METRICS_PATH.read_text(encoding="utf-8"))
        if current.get("review_status") != "preliminary_pending_user_confirmation":
            raise ValueError("current metrics are neither confirmed nor the expected preliminary source")
        shutil.copyfile(METRICS_PATH, PRELIMINARY_METRICS_ARCHIVE)
    archive = json.loads(PRELIMINARY_METRICS_ARCHIVE.read_text(encoding="utf-8"))
    if archive.get("review_status") != "preliminary_pending_user_confirmation":
        raise ValueError("preliminary metrics archive has an unexpected status")
    return archive


def promote_metrics(preliminary: dict) -> dict:
    confirmed = copy.deepcopy(preliminary)
    confirmed["reviewer"] = CONFIRMED_REVIEWER
    confirmed["review_status"] = CONFIRMED_STATUS
    confirmed["notes"] = [
        "Scores were generated by a Codex-assisted review and confirmed by the user.",
        "The user confirmed correctness, faithfulness, hallucination, and over-refusal labels.",
        "The frozen final split was not used.",
    ]
    for method in confirmed["methods"].values():
        method["scoring_status"] = CONFIRMED_STATUS
        method["reviewer"] = CONFIRMED_REVIEWER
    METRICS_PATH.write_text(json.dumps(confirmed, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return confirmed


def update_comparison() -> None:
    comparison = json.loads(COMPARISON_JSON.read_text(encoding="utf-8"))
    comparison["human_scoring_status"] = CONFIRMED_STATUS
    for method in comparison["methods"]:
        method["answer_correctness_status"] = CONFIRMED_STATUS
        method["faithfulness_status"] = CONFIRMED_STATUS
        method["hallucination_status"] = CONFIRMED_STATUS
    COMPARISON_JSON.write_text(json.dumps(comparison, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    rows = read_csv(COMPARISON_CSV)
    for row in rows:
        row["answer_correctness_status"] = CONFIRMED_STATUS
        row["faithfulness_status"] = CONFIRMED_STATUS
        row["hallucination_status"] = CONFIRMED_STATUS
    write_csv(COMPARISON_CSV, rows, list(rows[0]))

    markdown = COMPARISON_MD.read_text(encoding="utf-8")
    markdown = markdown.replace(
        "- Human correctness, faithfulness, and hallucination scores are still pending.",
        "- Semantic scores are user-confirmed; the original Codex-assisted scoring draft is retained for audit.",
    )
    COMPARISON_MD.write_text(markdown, encoding="utf-8")


def promote_pilot_run_metrics(metrics: dict) -> None:
    metric_names = (
        "answer_correctness",
        "evidence_faithfulness",
        "hallucination_rate",
        "over_refusal_rate",
    )
    for method in ("vector_rag", "graph_only", "proposed", "no_verifier"):
        path = PILOT_REPORT_DIR / f"{method}_pilot.json"
        report = json.loads(path.read_text(encoding="utf-8"))
        for metric_name in metric_names:
            source = metrics["methods"][method][metric_name]
            report["metrics"][metric_name] = {
                "value": source["value"],
                "numerator": source["numerator"],
                "denominator": source["denominator"],
                "status": CONFIRMED_STATUS,
                "note": "Semantic score generated with Codex assistance and confirmed by the user.",
            }
        report["notes"] = [
            note
            for note in report.get("notes", [])
            if note != "Human correctness, faithfulness, and hallucination metrics remain pending manual review."
        ]
        confirmation_note = "User-confirmed semantic metrics attached after the pilot run; automatic metrics are unchanged."
        if confirmation_note not in report["notes"]:
            report["notes"].append(confirmation_note)
        path.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_summary(comparison: dict, metrics: dict) -> None:
    fields = [
        "method",
        "decision_accuracy",
        "answer_correctness",
        "evidence_faithfulness",
        "retrieval_recall_at_5",
        "path_validity",
        "refusal_accuracy",
        "hallucination_rate",
        "over_refusal_rate",
        "mean_latency_ms",
        "review_status",
    ]
    rows = []
    for auto_row in comparison["methods"]:
        method = auto_row["method"]
        human_row = metrics["methods"][method]
        rows.append(
            {
                "method": method,
                "decision_accuracy": auto_row["decision_accuracy"],
                "answer_correctness": human_row["answer_correctness"]["value"],
                "evidence_faithfulness": human_row["evidence_faithfulness"]["value"],
                "retrieval_recall_at_5": auto_row["retrieval_recall_at_5"],
                "path_validity": auto_row["path_validity"],
                "refusal_accuracy": auto_row["refusal_accuracy"],
                "hallucination_rate": human_row["hallucination_rate"]["value"],
                "over_refusal_rate": human_row["over_refusal_rate"]["value"],
                "mean_latency_ms": auto_row["mean_latency_ms"],
                "review_status": CONFIRMED_STATUS,
            }
        )
    write_csv(SUMMARY_CSV, rows, fields)

    def fmt(row: dict, name: str) -> str:
        value = row[name]
        return "n/a" if value is None else f"{value:.4f}"

    lines = [
        "# Pilot Metrics Summary",
        "",
        "Automatic experiment metrics are combined with user-confirmed semantic scores.",
        "The scores were generated by a Codex-assisted review and subsequently confirmed by the user.",
        "They are not an independent multi-rater annotation or a statistical significance test.",
        "The frozen final split was not rerun.",
        "",
        "| Method | Decision acc. | Answer correctness | Faithfulness | Recall@5 | Path validity | Refusal acc. | Hallucination | Over-refusal | Latency (ms) |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for row in rows:
        lines.append(
            f"| {row['method']} | {fmt(row, 'decision_accuracy')} | {fmt(row, 'answer_correctness')} | "
            f"{fmt(row, 'evidence_faithfulness')} | {fmt(row, 'retrieval_recall_at_5')} | "
            f"{fmt(row, 'path_validity')} | {fmt(row, 'refusal_accuracy')} | "
            f"{fmt(row, 'hallucination_rate')} | {fmt(row, 'over_refusal_rate')} | "
            f"{fmt(row, 'mean_latency_ms')} |"
        )
    lines.extend(
        [
            "",
            "Interpretation: Proposed has the strongest user-confirmed correctness and faithfulness among the four methods, while its main verified gain is 4/4 no-answer refusal. The observed hallucination rate is zero in this reviewed pilot sample; this does not imply that the system cannot hallucinate outside the reviewed setting.",
        ]
    )
    SUMMARY_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")


def promote_error_analysis() -> None:
    text = ERROR_DRAFT.read_text(encoding="utf-8")
    text = text.replace("# Pilot Error Analysis Draft", "# Pilot Error Analysis (User-confirmed scores)", 1)
    text = text.replace(
        "This is an agent-assisted preliminary draft. It is not a claim of independent human annotation.\nThe final report should retain the raw answers and have a reviewer confirm or revise each score.",
        "This error analysis is based on user-confirmed semantic scores. The original Codex-assisted draft and raw answers remain available for audit. It is not a claim of independent multi-rater annotation.",
    )
    text = text.replace(
        "1. Confirm correctness and faithfulness scores against the full answer and cited source chunks.\n",
        "1. Scores and cited-source judgments were confirmed by the user; retain the raw answers and cited chunks for audit.\n",
    )
    ERROR_CONFIRMED.write_text(text, encoding="utf-8")


def main() -> int:
    _, confirmed_rows = promote_csv()
    preliminary = load_preliminary_metrics()
    metrics = promote_metrics(preliminary)
    promote_pilot_run_metrics(metrics)
    update_comparison()
    comparison = json.loads(COMPARISON_JSON.read_text(encoding="utf-8"))
    write_summary(comparison, metrics)
    promote_error_analysis()
    print(f"OK: confirmed rows={len(confirmed_rows)}")
    print("OK: score values unchanged from preliminary source")
    print(f"OK: metrics_status={metrics['review_status']}")
    print(f"OK: archived_preliminary_metrics={PRELIMINARY_METRICS_ARCHIVE}")
    print(f"OK: confirmed_scoring={CONFIRMED_CSV}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
